version: "3.5"

services:
  frontend:
    build:
      target: production
      args:
        BACKEND_URL: ${FRONTEND_API}
        OAUTH_AUTHORITY: ${OAUTH_AUTHORITY}
        OIDC_REDIRECT_HOST: ${FRONTEND_REDIRECT_HOST}
        OIDC_CLIENT_ID: ${FRONTEND_OIDC_CLIENT_ID}
    labels:
      traefik.http.routers.webapp.tls: true
      traefik.http.routers.webapp.tls.certResolver: letsEncrypt
      traefik.http.routers.webapp.entrypoints: websecure

  backend_v1:
    build:
      target: production
    environment:
      FLASK_DEBUG: "False"
      GUNICORN_WORKERS: 1
    labels:
      traefik.http.routers.backend.tls: true
      traefik.http.routers.backend.tls.certResolver: letsEncrypt
      traefik.http.routers.backend.entrypoints: websecure

  reverse-proxy:
    command:
      # for some reason extending does *not* merge command, so I'm pasting these here as well
      - "--entrypoints.web.address=:80"
      - "--providers.docker"

      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsEncrypt.acme.storage=/etc/traefik/mounted/acme.json"
      - "--certificatesresolvers.letsEncrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsEncrypt.acme.tlschallenge=true"
    volumes:
      - ./traefik/:/etc/traefik/mounted/
    ports:
      - "443:443"
