version: "3.5"

services:
  frontend:
    build:
      target: development

  backend_v1:
    build:
      target: development
    environment:
      FLASK_DEBUG: "True"
    volumes:
      - ./backend/:/app
